// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbESLkq4WBwvMHAuNqilhN2CevTC77Ybk',
    appId: '1:408006768938:web:13034e6e70b87d26aec653',
    messagingSenderId: '408006768938',
    projectId: 'chargex-99071',
    authDomain: 'chargex-99071.firebaseapp.com',
    storageBucket: 'chargex-99071.firebasestorage.app',
    measurementId: 'G-WSYKXK45JP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB96DU4wDdRH5mf23xuItVcbHlextGUaxM',
    appId: '1:408006768938:ios:e8f3b9919bc6b08daec653',
    messagingSenderId: '408006768938',
    projectId: 'chargex-99071',
    storageBucket: 'chargex-99071.firebasestorage.app',
    iosClientId: '408006768938-i58qb5bf3bebh603bks7id9aue1kf3tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chargex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbESLkq4WBwvMHAuNqilhN2CevTC77Ybk',
    appId: '1:408006768938:web:b07853a1e03eb65caec653',
    messagingSenderId: '408006768938',
    projectId: 'chargex-99071',
    authDomain: 'chargex-99071.firebaseapp.com',
    storageBucket: 'chargex-99071.firebasestorage.app',
    measurementId: 'G-ZHGEJE44SV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB96DU4wDdRH5mf23xuItVcbHlextGUaxM',
    appId: '1:408006768938:ios:e8f3b9919bc6b08daec653',
    messagingSenderId: '408006768938',
    projectId: 'chargex-99071',
    storageBucket: 'chargex-99071.firebasestorage.app',
    iosClientId: '408006768938-i58qb5bf3bebh603bks7id9aue1kf3tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chargex',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnSmbQFaoL5kMv3cg45u9D26NiSAZSCRk',
    appId: '1:408006768938:android:0e845798f96b7153aec653',
    messagingSenderId: '408006768938',
    projectId: 'chargex-99071',
    storageBucket: 'chargex-99071.firebasestorage.app',
  );

}