// lib/main.dart
import 'package:chargex/screens/splash_screen.dart';
import 'package:chargex/screens/nearby_screen.dart'; // <-- existing
import 'package:chargex/screens/trip_planner_screen.dart'; // <-- new Trip Planner import
import 'package:chargex/screens/my_bookings_screen.dart';
import 'package:chargex/screens/station_detail_screen.dart';

import 'package:chargex/services/auth_service.dart';
import 'package:chargex/services/database_service.dart';
import 'package:chargex/services/location_service.dart';

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const ChargeXApp());
}

class ChargeXApp extends StatelessWidget {
  const ChargeXApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        Provider<AuthService>(create: (_) => AuthService()),
        Provider<DatabaseService>(create: (_) => DatabaseService()),
        Provider<LocationService>(create: (_) => LocationService()),
      ],
      child: MaterialApp(
        title: 'ChargeX',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          brightness: Brightness.dark,
          primaryColor: Colors.indigoAccent,
          scaffoldBackgroundColor: const Color(0xFF121212),
          colorScheme: const ColorScheme.dark(
            primary: Colors.indigoAccent,
            secondary: Colors.tealAccent,
            surface: Color(0xFF1E1E1E),
          ),
          inputDecorationTheme: InputDecorationTheme(
            filled: true,
            fillColor: Colors.grey.withOpacity(0.1),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: BorderSide.none,
            ),
            labelStyle: TextStyle(color: Colors.grey[400]),
          ),
          elevatedButtonTheme: ElevatedButtonThemeData(
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.indigoAccent,
              foregroundColor: Colors.white,
              padding: const EdgeInsets.symmetric(vertical: 16),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12),
              ),
              textStyle: const TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
        ),

        // Use HomeWrapper so we can show a FAB that opens Trip Planner
        home: const HomeWrapper(),

        // Routes (add the Trip Planner route here)
        routes: {
          '/nearby': (_) => const NearbyScreen(),
          '/my-bookings': (_) => const MyBookingsScreen(),
          '/trip': (_) => const TripPlannerScreen(),
          // Station Detail Screen (It expects arguments)
          '/station': (context) {
            final stationId = ModalRoute.of(context)!.settings.arguments as String;
            return StationDetailScreen(
              stationId: stationId,
              stationName: "Station",
            );
          },
        },
      ),
    );
  }
}

/// HomeWrapper shows your existing SplashScreen as the main body,
/// and adds a FloatingActionButton so you can open the Trip Planner quickly.
class HomeWrapper extends StatelessWidget {
  const HomeWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // We place your SplashScreen inside the Scaffold body.
      // If your SplashScreen itself contains a Scaffold, Flutter will nest them,
      // which is usually okay. If your SplashScreen requires specific usage,
      // you can instead replace this with the real main/home screen widget.
      body: const SplashScreen(),

      // Floating action button to open Trip Planner
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.of(context).pushNamed('/trip');
        },
        backgroundColor: Colors.indigoAccent,
        child: const Icon(Icons.alt_route),
        tooltip: 'Open Trip Planner',
      ),
    );
  }
}
